# Autogenerated wrapper script for svg2pdf_jll for x86_64-w64-mingw32
export svg2pdf

JLLWrappers.@generate_wrapper_header("svg2pdf")
JLLWrappers.@declare_executable_product(svg2pdf)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        svg2pdf,
        "bin\\svg2pdf.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
